[publy]
title = "퍼블리"
url = "https://publy.co/topic/all?fr=top-navi"
entrySelector = "div.row div.col-4.mb-9"
titleSelector = "h6.text-gray-900.font-weight-normal.font-size-medium.text-truncate-2.leading-tight.mb-0"
linkSelector = "a.d-block.position-relative"
contentSelector = "p.font-size-xsmall.text-gray-600"
waitUntil = "networkidle"